# Generated by Django 3.0.8 on 2020-07-14 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200712_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 17, 58, 17, 129522, tzinfo=utc)),
        ),
    ]
