# Generated by Django 3.0.8 on 2020-07-15 05:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200714_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 5, 5, 7, 793781, tzinfo=utc)),
        ),
    ]
